# Generated by Django 3.0.5 on 2020-07-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200717_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pubhlish',
            new_name='publish',
        ),
    ]
